# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 13:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(verbose_name='Monto o cantidad')),
                ('payment_date', models.DateTimeField(verbose_name='Fecha de pago')),
                ('stripe_id', models.CharField(max_length=255, verbose_name='ID Cliente recurente de Stripe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Datos de suscripción',
                'verbose_name': 'Datos de suscripción',
            },
        ),
    ]
